### ISSUE TITLE
Define the exact Solr version to use

### ISSUE THREAD

**Issue by dpacassi** [wodby/solr#10]
I'm currently using [docker4drupal](https://github.com/wodby/docker4drupal) with Solr, which works great, thanks for it!
I've been trying to find the right `SOLR_TAG` value to get Solr `6.6.1` with my `docker-compose.yml` file.

This is what I was able to find out:
`SOLR_TAG=6-4.1.2` gets Solr `6.6.6`
`SOLR_TAG=6-2.3.0` gets Solr `6.6.2`
`SOLR_TAG=6.6-2.2.0` gets Solr `6.6.0`

Is there a `SOLR_TAG` I can use to get Solr `6.6.1`?
Or (better) can I define somewhere the `SOLR_VER` value so that I can get Solr in the version `6.6.1`?

Thanks a lot for your support!

**Comment by csandanov** [comment]
We do not provide tags for patch releases, we have 6.6 which has the latest patch release 6.6.6. Our image is based on the versions in https://hub.docker.com/_/solr. Normally there shouldn't be any compatibility issues between patch releases but if you need 6.6.1 specifically you can perhaps search through [release](https://github.com/wodby/solr/releases) and find a stability tag where 6.6.1 update was released.
