### ISSUE TITLE
Bring in new Drupal jump-start configsets

### ISSUE THREAD

**Issue by bradjones1** [wodby/solr#14]
[This issue](https://www.drupal.org/node/3070455) outlines a parallel, automated configset generation and packaging process for the Drupal module. Through this new process, sensible-default english-language config sets are generated with the explicit goal of making cloud-native/Dockerized workflows faster and easier, while also expanding support for hosted Solr.

The [download script](https://github.com/wodby/solr/blob/master/search-api-solr/download.sh) currently rejects any version which ships only templates. This could be changed to bring in the jumpstart configsets.

Additionally, the download script does not currently recognize semantic versioning in recognizing releases; [this line](https://github.com/wodby/solr/blob/master/search-api-solr/download.sh#L14) could/should be changed to use the ["current" and "7.x"](https://www.drupal.org/drupalorg/docs/apis/update-status-xml) compatibility tags from the Drupal updates API to capture both 7.x and 8.x.

**Comment by bradjones1** [comment]
FYI we've forked this at https://github.com/fruition/solr to do exactly this (with credit where credit is due of course.) Thanks!

**Comment by csandanov** [comment]
Thank you, the support for jump-start configsets now added

**Comment by bradjones1** [comment]
@csandanov The change you made [here](https://github.com/wodby/solr/commit/ca78a4f9159b4a2685ab6d785bc41297cf22919a#diff-ec4289cfb371039a2af2408d5c4ae4f6R14) to the `current` endpoint only means no more config sets for 7.x, by the way... `current` only returns 8.x+.

**Comment by csandanov** [comment]
Right, thanks, fixed now
