### ISSUE TITLE
search_api_solr:4.2.1 needs new config

### ISSUE THREAD

**Issue by mralexho** [wodby/solr#18]
`SOLR_CONFIG_SET="search_api_solr_4.1.6"`
`SOLR_TAG=8-4.13.0`

Running search_api_solr:4.2.1 results in 

> You are using outdated Solr configuration set. Please follow the instructions described in the README.md file for setting up Solr.

**Comment by csandanov** [comment]
Hi Alex, not the best place for this issue as it relates to Wodby Cloud not to the image. We will update the default config set for solr for drupal service/stack from `4.1.6` to `4.2.3` with the upcoming stacks update but you will still have to recreate your core to update the config set. And AFAIK this warning doesn't really mean that that there are changes in the config set, it just checks that the version of the module matches the version inside the config set that updated with the module but usually it doesn't have any changes at all.

**Comment by mralexho** [comment]
Thanks @csandanov, I saw a similar thread https://github.com/wodby/solr/issues/9 and assumed it was here. Agreed, we've been running okay with `4.1.6` without any issues but thought it'd be worthwhile to update.

**Comment by ginho** [comment]
Hello to all,
I am seeking how clarification for this warning...
I am having similar issue and I am using slor in the cloud. Not sure is the is a drupal for slor issue. 

----------
>  [warning] Message: There have been some configuration changes. It is advisable to download and 
> deploy an updated config.zip to your Solr server.
> 
>  [warning] Message: A new Solr field type has been installed due to configuration changes. It is 
> advisable to download and deploy an updated config.zip to your Solr server.
> 

----------

Thank you Mario
