### ISSUE TITLE
define instanceDir on make create

### ISSUE THREAD

**Issue by iampuma** [wodby/solr#2]
Currently it is not possible to set the instanceDir when creating a new core:

  docker-compose exec solr make core=MYNEWCORE -f /usr/local/bin/actions.mk

I would like to be able to do the following

  docker-compose exec solr make core=MYNEWCORE instanceDir=/opt/solr/server/solr/mycores -f /usr/local/bin/actions.mk

I guess this would have to be a change in the 'actions.mk' script?

**Comment by csandanov** [comment]
`instance_dir` param has been added for the core create action, defaults to core name, available with [`-2.4.0`](https://github.com/wodby/solr/releases/tag/2.4.0) release
