### ISSUE TITLE
`init_solr` should use authentication when creating default core and collection

### ISSUE THREAD

**Issue by baumanno** [wodby/solr#20]
I'm trying to hook this solr-container up to a Drupal-instance, using https://github.com/wodby/docker4drupal.
I followed the steps outlined at https://wodby.com/docs/1.0/stacks/drupal/local/#solr-search-api, where it mentions:
> Access Solr container via `make shell solr` and run `make init -f /usr/local/bin/actions.mk`. This will enable authentication for Solr Cloud mode and create a collection named `default` that will use `_default` config set.

However, the collection is never created: when I access the solr admin panel, I see no cores and no collections, and communication with Solr SearchAPI in Drupal cannot be established.

I believe this is due to the fact that `init_solr` first sets up a new authentication with user:pass, and then goes on to call the solr-API via curl *without* user:pass:

https://github.com/wodby/solr/blob/02379f815538e986850cc818f980b9c83fe48693/bin/init_solr#L13-L24

When I run `make init -f /usr/local/bin/actions.mk` in the solr-container, then execute the curl-call for listing collections manually, I get this:

```bash
/opt/solr/server/solr $ curl -s "http://solr:8983/solr/admin/collections?action=LIST"
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 401 require authentication</title>
</head>
<body><h2>HTTP ERROR 401 require authentication</h2>
<table>
<tr><th>URI:</th><td>/solr/admin/collections</td></tr>
<tr><th>STATUS:</th><td>401</td></tr>
<tr><th>MESSAGE:</th><td>require authentication</td></tr>
<tr><th>SERVLET:</th><td>default</td></tr>
</table>

</body>
</html>
```

I believe the call that sets up authentication should either be made *after* creating cores/collections, or the respective curl-calls should be provided the newly created credentials.

**Comment by csandanov** [comment]
You're right, we should create the collection before setting up the auth, thank you for reporting this
