### ISSUE TITLE
The right way to edit conf

### ISSUE THREAD

**Issue by arrubiu** [wodby/solr#3]
I would like to add some new conf to solr configuration (spellcheck and "partial string search").
How should I provide these configurations?

**Comment by csandanov** [comment]
Added new section https://wodby.com/docs/stacks/solr/#customizing-solr-core. It contains how to customize configs but not how to enable specific features, I suggest visiting [the official solr documentation](http://lucene.apache.org/solr/guide/) for that. PRs to docs are welcomed
