### ISSUE TITLE
Error bringing up container with environment variable

### ISSUE THREAD

**Issue by jordotech** [wodby/solr#4]
I'm trying to run this container but am unable to get it started

`docker run --name solr -d -p 8983:8983 -t wodby/solr:5.5 -e "SOLR_DEFAULT_CONFIG_SET=search_api_solr_7.x-1.9"`

I get the error
ERROR: Unsupported example SOLR_DEFAULT_CONFIG_SET=search_api_solr_7.x-1.9! Please choose one of: cloud, dih, schemaless, or techproducts

What am I doing wrong here?

**Comment by csandanov** [comment]
See [docker run usage](https://docs.docker.com/engine/reference/run/), you're specifying an env var as a command

**Comment by jordotech** [comment]
For anyone else running into this, the solution was to move the -e flag directly after the run portion so

`docker run -e "SOLR_DEFAULT_CONFIG_SET=search_api_solr_7.x-1.9" --name solr -d -p 8983:8983 -t wodby/solr:5.5`

I don't understand why it would matter the order of the flags but it apparently does
