### ISSUE TITLE
Cannot mount volumes

### ISSUE THREAD

**Issue by DuaelFr** [wodby/solr#6]
Hi,

I'm trying to mount some volumes to provide custom configsets and predefined cores.
The problem is that docker-compose mounts volumes as uid 1000 what works well in your php containers but not in this one because the solr user uid is 8983.
I can't find any way to force docker-compose to use another uid while mouting the volume.

Thanks a lot!

**Comment by csandanov** [comment]
Have you tried setting `user: root` in your docker-compose?

**Comment by DuaelFr** [comment]
We finally had to create our own image from wodby's where we copied the files instead of using a volume. Using `user: root` was not an option according to our security restrictions.
