### ISSUE TITLE
search_api_solr_8.x-3.0 owned by root

### ISSUE THREAD

**Issue by lukestirk** [wodby/solr#8]
Due to https://www.drupal.org/project/search_api_solr/issues/3015993 I have been removing the last line of solrcore.properties when the container is built. After upgrading to the latest version of search_api_solr and pulling the latest build of this image I am no longer able to do this due to search_api_solr_8.x-3.0 been owned by root.

Can this be changed? alternatively is solr.install.dir=../../.. needed in  solrcore.properties

**Comment by csandanov** [comment]
Fixed in latest
